README.md
This PR adds a section to the README that encourages consumers of `@github/hotkey` to consider users where keyboard shortcuts can actually be a drawback.
Reference: https://twitter.com/NickColley/status/1088609831580323840
=> Add a note about accessibility to README

README.md
`document.querySelector` returns either a `null` or the first of matching elements. It must be `document.querySelectorAll` to work as intended.
=> updated example code in readme.md

README.md, src/index.js, src/index.js.flow, test/test-radix-trie.js, test/test.js
Allow the hotkey to be passed to the registering function (`install`) as an optional parameter, rather than requiring the use of the `data-hotkey` attribute. And update and expand the documentation (closes #5).
=> Don't mandate the use of the `data-hotkey` attribute

README.md, src/index.js, src/index.js.flow, test/test.js
Rather then registering a global keyhandler for the consumers of `github/hotkey`, this PR exposes the keydown handler and puts the onus of registering it on the consumer.
cc/ @muan
=> Register keydown handler on first install

src/utils.js, test/test.js
Instead of focusing radio and checkbox input elements we should simulate click them like how we do with buttons and links.
=> Support of checkbox and radio input elements

README.md, src/utils.js
Closes #22.
@koddsson: As discussed in our 1:1, I didn't like the idea of allowing `.click()` on any odd `role="button"` elements, but I also felt that even requiring `[tabindex]` with `[role]` would be a half measure. 
So I propose–– Instead of adding `role="button"` into the approved list of clickable selectors, we remove the constraint altogether. This will also allow hotkey to work on Custom Elements with `delegatedFocus` (https://github.com/github/details-dialog-element/issues/26). 
To ease my own concern with hotkey getting abused (😬), I added a paragraph to the Accessibility considerations in the README.
=> Trigger click on anything 

src/hotkey.js, test/test.js
This library currently does not have support for interacting with the `shift` plane of keyboard shortcuts. You can interact with them _coincidentally_ by using a capital letter key, e.g. `Control+P` is the equivalent of `Control+Shift+P`. The problem is that on macos the `Meta+Shift+` plane is always lowercase, and as such is inaccessible using this library.
This fixes the issue by adding `shiftKey` as `Shift+` in the `hotkey` function.
=> fix: enable support for meta+shift plane

src/hotkey.js, test/test.js
I raised https://github.com/github/hotkey/pull/25 in the hopes of adding support for the `meta+shift` plane, but this broke shortcuts like `data-key=B` because it is expecting `data-key=Shift+B`. The tests were passing because our tests have capitals without `shiftKey = true`.
This fixes the breakage in 1.3.1 by adding a check to _only_ add the `Shift+` modifier if `event.key.toUpperCase() !== event.key`, allowing for both `data-key="Meta+Shift+b"`/`data-key="B"`
=> fix: support for meta+shift plane while retaining short upper chars

package.json, rollup.config.js
We're inadvertently transforming the `class` and `for…of` syntax in the module output file. Browsers that support modules also support this syntax, so just strip Flow types during compilation.
=> Remove syntax transformations in module output

src/index.ts
Ref: https://github.com/github/github/issues/147670
`preventDefault` would need to be called before the event bubbles up to document.
cc @t-hugs @lerebear
=> Check defaultPrevented before triggering hotkey

src/hotkey.ts, test/test.js
There's a bug when trying to use a symbol like <code>Control+Shift+&#96;</code> as the hotkey. See https://github.com/github/github/pull/175242#discussion_r603640676
Because of this line, &#96; doesn't have an uppercase value. 
I'm trying to fix by checking the `KeyboardEvent.code` https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code value for "Key" which should be alpha numeric.
=> Fix for bug where we can't use symbols

src/index.ts, src/radix-trie.ts
As part of https://github.com/github/hotkey/pull/39 we refactored the `RadixTrie` class to be a `RadixTrie<T>` which makes it much easier to reason about the Leaf node properties.
This is that refactoring as a standlone PR, making https://github.com/github/hotkey/pull/39 smaller.
=> style: give RadixTrie a T

src/hotkey.ts, test/test.js
This fixes a regression in the eventToHotkeyString function which was caused by trying to normalise the event.key toUpperCase. The regression was because on macos the "Meta+Shift" plane is always lowercase, which is contrary to other operating systems. This is a regression because that was expected behavior as part of this package, and the fix in `1.4.3` broke this expectation while trying to fix another bug.
This change respects the `event.key` spacing, and elides the shift key only when the event.key matches case, returning `Meta+Shift+p` as a viable shortcut.
/cc @jonrohan
=> fix: respect key case, elide shift only when case matches

examples/index.html, src/index.ts, test/test.js
Add support for scoped hotkeys when the `data-hotkey-scope` attribute is specified.
For example: 
```.html
<button data-hotkey="Control+P" data-hotkey-scope="text-area-1"> Button 1 </button>
<textarea id="text-area-1"> </textarea>
<textarea id="text-area-2"> </textarea>
```
Currently `github/hotkey` only supports global hotkeys but increasingly we are seeing a need for hotkey actions that can be triggered from a textarea.  Rather than relying on custom hotkey implementations for scoped shortcuts, we should expand this library.
Co-authored-by: @keithamus
=> Add support for scoped hotkey

.github/workflows/publish.yml
Add a CI script to publish packages automatically for us.
We've had difficulty in the past with publishing things in a reliable way. Forcing devs to publish on their local machines can mean all sorts of things:
- Perhaps they fail to run a command like `npm ci` which means deps are out of date, if compiling code this can affect the published artefact.
- Perhaps they've got extra files in their repository such as editor session files or notes files or unstaged files - this can sometimes accidentally get included
- We aren't always the best at setting up the dual-publish workflow, publishing to both GPR and npm. So some packages get inconsistently published to one or the other.
- Publishing packages can be scary! What if I missed something? It's a nerve wracking experience!
Additional pains …
=> build: auto publish releases

src/index.ts, src/utils.ts, test/test.js
This adds a new event: `hotkey-fire` which is dispatched on the element to fire (non bubbling, cancelable).
If it is cancelled the default action of click/focus is not triggered, which leaves developers to implement their own behaviour with some custom JS.
The point of this feature is that we can add `data-hotkey` to other types of elements than just form controls and buttons/links and trigger custom behaviours, while delegating/centralising the hotkey behaviour to this library. By listening to this event instead of `keydown` we can bind to advanced sequential keyboard shortcuts.
=> feat: dispatch event on fireDeterminedAction

src/index.ts
For some elements which have invalid query selector values in the ID, for example a space character, having the id selector unquoted will cause a DOMException. This is easily mitigated by wrapping this selector in quotes.
=> Fix querySelector by quoting templated value

examples/hotkey_mapper.html
relates to #54
This PR adds a tool to the `/examples` folder that allows a user to determine the correct hotkey string (as returned from `eventToHotKeyString`) for the given key combination. This tool could be a useful reference for users wanting to determine the correct hotkey string for their shortcut.
See the attached screen cast of the tool in action:
https://user-images.githubusercontent.com/2694/146098224-dfbd7a0c-9caa-470f-b81f-f850b3b56cbf.mov
=> Add tool to generate correct hotkey string for a given key combination

README.md, examples/hotkey_mapper.html
This PR adds a more detailed section documenting the hotkey string grammar. It also does a few other things:
1. Adds a simple example of usage at the very top as a TLDR
1. Swaps the order of the "Basic" usage (HTML and JS) and the more advanced topics like hotkey string format and accessibility. 
2. links to the Hotkey Mapper tool.
2. Fixes a layout issue in the Hotkey Mapper tool.
You can see the updated REAME here https://github.com/github/hotkey/blob/41c95f103f6e61e47ec43a83bae8edb30bc980e9/README.md
=> Update hotkey README to document hotkey string format

src/hotkey.ts, test/test.js
resolves #60 
This PR fixes a bug where `eventToHotkeyString` was returning a "double modifier" for a key-combination where a modifier key (`Control`, `Alt`, `Meta`, or `Shift`) is also the `event.key`.
This PR updates `eventToHotkeyString` so that the resulting string still presents modifiers in a consistent order. 
For more details see #60 
| Before | After |
| ---| --- |
| <img width="712" alt="Screen Shot 2021-12-15 at 9 50 36 AM" src="https://user-images.githubusercontent.com/2694/146208754-ed8f8cc9-3c86-4e7c-9aa5-c21c20d2da08.png"> | <img width="670" alt="Screen Shot 2021-12-16 at 5 58 21 PM" src="https://user-images.githubusercontent.com/2694/146461256-15289492-7e1e-4ec4-806f-3c8359877fe5.png"> |
https://user-images.githubusercontent.com/2694/146461487-c3832946-788c-47be-a3f3-eadfe7 …
=> fixes `eventToHotkeyString` returns doubled "modifier" when "key" is a modifier

README.md
The `data-hotkey-scope` feature is not mentioned in the README.
It's shown in the example, but it's easy to miss, or at least that's what happened to me. I spotted it while reading the source code, otherwise I wouldn't have discovered it.
Feel free to close if you are not interested in the change or ask for edits.
This package is awesome, thanks for creating it! 🙏
=> Explain how to scope hotkeys in README

src/utils.ts, test/test.js
I would like to allow hotkeys when focusing on `file` input elements by updating `isFormField` to return false for input elements with type `file`. 
`file` inputs are similar to `submit` or `radio` where a user needs to click on them for some interaction and can't freely type text. Therefore it should be fine to allow hotkeys when focused this kind of input.
=> Allow hotkeys when focusing on `file` input elements

examples/demo.html, examples/hotkey_mapper.html, examples/index.html, package-lock.json
Improves the mapper tool UX to fix #61 and make it easier to use:
- Replaces the output container with an `input` element so we automatically get focus handling and indication
- This element has the `application` role with "Input Capture" `aria-roledescription`. This indicates that this is not a normal text input and that keyboard events will be captured and discarded
- Adds `aria-live` and `aria-atomic` to read out the hotkey string when it changes
- Adds `aria-labelledby` and `aria-describedby` for semantic label & description associations to help screen reader users get oriented
- Adds `autofocus` so the input is focused on load. This is usually to be avoided, but in this case there is only one reasonable place for focus to land on the page and it is expected that the page will 'work' …
=> Improve mapper tool accessibility

.github/workflows/publish.yml
Noticed that we aren't publishing [provenance](https://github.blog/2023-04-19-introducing-npm-package-provenance/) with the releases (probably because we haven't released since it was introduced 🙂). It's easy to set up so I figured I'd just do it so we can have it in `2.2`.
=> Add npm package provenance in release workflow

src/hotkey.ts
A `HotkeyString` is a valid `SequenceString` but with only one item in the sequence. So anything that accepts `SequenceString` should also accept `HotkeyString`.
This PR makes `HotkeyString` extend `SequenceString` to allow for this.
This felt a little backwards to me because sequences are built from hotkeys, not the other way around, but it is correct. I made a simple [demo](https://www.typescriptlang.org/play?#code/MYewdgzgLgBGICcC2BDANgSwF4FMAmAEiFANY4CeAQgimHjALwwDK5SARiGgBQDk8ydNnxFSFXgEoAUDgAeAB0Swo5eThgA5RKky5CxMuWZQEGMAHNGm7UL3McARwCuOMMBzHTFmADIYAbwBtAR1hfTEqGjoAXQAuGBMXAF8pKVBIWBDbfHtnV3dqWnomVg4uPizdHMcXNxxJGQUlBNV1LUEqvFza908zSyZoL0s-IMqw7vycQpj4xJwUtPBoGAALAworACIULZgUCGsOsNFDPosljJgIGqntlBh2PYOj0LtbuvPzVPSVqFX+hAACqrFBQACCwHc8igkzqEGY6ycaDwkOhUFOFEOTG4NzydXi7Te1XxvRM-QkjAAfAE …
=> Make `NormalizedHotkeyString` extend `NormalizedSequenceString`

README.md
This just updates the link to the hotkey mapper tool to point to the new location.
=> fix link to hotkey mapper tool

.github/workflows/publish-pages.yml
Changes the target branch for publishing Pages from `master` to `main`. I meant to fix this in https://github.com/github/hotkey/pull/96 but I guess I overlooked it.
=> Fix default branch name in Pages publish workflow

README.md, src/hotkey.ts, test/test.js
Adds support for `Space` and `Plus` by mapping them from `+` and ` ` `event.key` names. Closes #https://github.com/github/hotkey/issues/45. Also adds tests and updates docs.
NOTE: This appears to be a breaking change at first glance because it changes the hotkey strings that would be generated for an event. But to match these events, strings like `Control++` and `Control+  g` would have to be used. This wouldn't have worked because we are splitting by `+` and ` ` already (ie, in `expandHotkeyToEdges`). So I don't think this can break any existing code.
=> Add support for `Space` and `Plus`

src/hotkey.ts, src/macos-symbol-layer.ts
We can avoid future potential conflicts between regular keys and symbol plane keys by not checking the symbol plane map unless `Alt` is pressed. This is an easy safeguard that should make bugs like the one that https://github.com/github/hotkey/pull/113 fixed less likely to happen in the future.
=> Don't use symbol plane unless `Alt` is pressed

pages/hotkey_mapper.html
Adds a "your user agent" section to the hotkey mapper tool. This will help us debug platforms if we ask someone to provide a screenshot of the result of some combination.
=> Add user agent to mapper tool

.github/workflows/publish.yml
The Publish/Release workflow [failed because it's still using Node 14](https://github.com/github/hotkey/actions/runs/7182982881/job/19560684597). This is an easy fix in the Actions config.
=> Use Node 16 for publishing

package.json
Moves `eslint-import-resolver-typescript` from `dependencies` to `devDependencies`
=> Move `eslint-import-resolver-typescript` to dev dependencies

README.md
Fixes an unneccessary /pages/ path-particle in the URI to the mapper tool.
=> fix: hotkey mapper URL

src/hotkey.ts, test/test-normalize-hotkey.js
When normalizing the hotkeys in an SSR environment, `localizeMod` breaks SSR with its direct `window.navigator` reference. 
This PR adds window checks to ensure safe SSR usage, updates types, and adds test coverage.
=> Make localizeMod SSR safe
